src/modules/grub/main.py

Source: https://wiki.archlinux.org/index.php/GRUB#UEFI_firmware_workaround
Please test before pulling!!!

grub: use uefi firmware workaround

---

src/modules/bootloader/main.py
src/modules/displaymanager/main.py
src/modules/dracut/main.py
src/modules/dummypython/main.py
src/modules/fstab/main.py
src/modules/grub/main.py
src/modules/grubcfg/main.py
src/modules/hwclock/main.py
src/modules/initcpio/main.py
src/modules/initcpiocfg/main.py
src/modules/initramfs/main.py
src/modules/keyboard/kbd-model-map
src/modules/localecfg/main.py
src/modules/machineid/main.py
src/modules/mount/main.py
src/modules/networkcfg/main.py
src/modules/packages/main.py
src/modules/services/main.py
src/modules/testmodule.py
src/modules/umount/main.py
src/modules/unpackfs/main.py

A basic Python code review that brings us closer to the PEP standards.  Also pulled the most recent version of 'kbd-model-map'.
This is a re-submission of my pull request from yesterday.  I shouldn't try to be productive on an hour of sleep. I tend to break things. lol  Nevertheless, let me know what you think and if any changes are required.
References:
https://www.python.org/dev/peps/pep-0008/
https://www.python.org/dev/peps/pep-0263/
http://cgit.freedesktop.org/systemd/systemd/log/src/locale/kbd-model-map

PEP Compliance and a Few Fixes

---

src/modules/bootloader/main.py
src/modules/displaymanager/main.py
src/modules/dummypython/main.py
src/modules/initcpiocfg/main.py
src/modules/mount/main.py

Just cleaning up a few unused imports.

Unused Imports

---

HACKING.md
README.md

Just cleaned up and reformatted the README.
Please see: https://github.com/Gormogon/calamares

README Reformat

---

src/modules/bootloader/main.py
src/modules/displaymanager/main.py
src/modules/dracut/main.py
src/modules/dummypython/main.py
src/modules/fstab/main.py
src/modules/grubcfg/main.py
src/modules/initcpio/main.py
src/modules/initcpiocfg/main.py
src/modules/initramfs/main.py
src/modules/machineid/main.py
src/modules/mount/main.py
src/modules/packages/main.py
src/modules/testmodule.py
src/modules/umount/main.py
src/modules/unpackfs/main.py

In-code documentation for Python jobmodules. This way new developers will better understand our modules. Please verify added doc strings and check if your module still works.

Python docstrings

---

src/calamares/CalamaresApplication.cpp
src/calamares/CalamaresApplication.h
src/calamares/main.cpp
src/calamares/progresstree/ProgressTreeModel.cpp
src/calamares/progresstree/ProgressTreeModel.h
src/libcalamares/PythonHelper.cpp
src/libcalamares/utils/CalamaresUtils.cpp
src/libcalamares/utils/Logger.cpp
src/libcalamaresui/Branding.h
src/libcalamaresui/Settings.h
src/libcalamaresui/modulesystem/ProcessJobModule.h
src/libcalamaresui/modulesystem/PythonJobModule.h
src/libcalamaresui/modulesystem/ViewModule.h
src/libcalamaresui/viewpages/AbstractPage.h
src/libcalamaresui/viewpages/ViewStep.h
src/libcalamaresui/widgets/QtWaitingSpinner.cpp
src/libcalamaresui/widgets/QtWaitingSpinner.h
src/modules/keyboard/KeyboardPage.h
src/modules/keyboard/keyboardwidget/keyboardpreview.cpp
src/modules/keyboard/keyboardwidget/keyboardpreview.h
src/modules/locale/timezonewidget/timezonewidget.cpp
src/modules/locale/timezonewidget/timezonewidget.h
src/modules/prepare/PreparePage.cpp
src/modules/users/UsersPage.cpp
src/modules/users/UsersViewStep.h

Aligning pointers to type as previously discussed with Teo.

Align Pointers

---

src/branding/default/branding.desc
src/libcalamaresui/Branding.cpp
src/libcalamaresui/Branding.h
src/modules/greeting/GreetingPage.cpp

Reverts calamares/calamares#209

Revert "add URL option in greeting page"

---

src/modules/bootloader/main.py
src/modules/mount/mount.conf

chroot/sys/firmware/efi/efivars is empty.
Mount it!

Fixes for grub efi

---

src/modules/bootloader/main.py
src/modules/displaymanager/main.py
src/modules/dracut/main.py

The title says it all.  Just a little cleanup to make things more readable and a fix for GDM auto-login.  This was caused by a simple typo.

GDM Auto-Login Bug Fix and PEP Cleanup

---

src/modules/bootloader/main.py
src/modules/fstab/main.py
src/modules/grubcfg/main.py
src/modules/hwclock/main.py
src/modules/initcpio/main.py
src/modules/initcpiocfg/main.py
src/modules/initramfs/main.py
src/modules/localecfg/main.py
src/modules/machineid/main.py
src/modules/mount/main.py
src/modules/networkcfg/main.py
src/modules/packages/main.py
src/modules/removeuser/main.py
src/modules/services/main.py
src/modules/umount/main.py
src/modules/unpackfs/main.py

This is the last of the PEP compliance review. All Python code has been reviewed.

Last PEP Cleanup

---

src/libcalamares/utils/CalamaresUtilsSystem.cpp
src/modules/locale/SetTimezoneJob.cpp

* Adjust modules for dont-chroot mode
* Write out to additional files for timezone stuff

Fix some issues when using dont-chroot

---

src/modules/users/UsersPage.cpp
src/modules/users/UsersPage.h
src/modules/users/UsersViewStep.cpp
src/modules/users/users.conf

Let me know if it is an issue this work was done in the choicepreview branch, it is what I'm working in and using.  If it is then will remove this fork and redo in master.
This change is tested to build and work in the GUI.

implement https://calamares.io/bugs/browse/CAL-341

---

src/modules/partition/core/PartUtils.cpp
src/modules/partition/gui/ChoicePage.cpp

Fixing: https://calamares.io/bugs/browse/CAL-360

implement free-space partition replace install

---

src/modules/networkcfg/main.py

Same as pull request #248, but from the correct branch so it does not include my unrelated commits.

networkcfg needs to copy resolv.conf in the chroot

---

src/modules/unpackfs/main.py

Support the already mounted loop fs (example in the blackPanther OS)

---

src/libcalamares/kdsingleapplicationguard/kdsingleapplicationguard.cpp

Fix spelling mistake

---

src/modules/grubcfg/main.py

This will add an extra rd.luks.uuid for encrypted swap if exists and will allow dracut to unlock it.

dracut : unlock encrypted swap if exists

---

src/modules/displaymanager/main.py

Since sddm.conf follows the INI format we can use configparser
with a few added options to properly parse the config and write
it out instead of manually parsing each line which is slow and
prone to error.
For eg. The old code would fail to parse a conf which had no
commented out User key but where the user had configured autologin
in Calamares.

Use configparser to parse sddm.conf

---

src/modules/dracut/main.py

Fixed pep8 whining in module dracut

---

src/modules/plymouthcfg/main.py

Fixed pep8 whining in module plymouthcfg

---

README.md

The nesting wasn't rendering properly in github.

Fix nested lists in README

---

src/modules/dummypython/main.py

Fixed pep8 whining in module dummypython

---

src/modules/machineid/main.py

Fixed pep8 whining in module machineid

---

src/modules/removeuser/main.py

Fixed pep8 whining in module removeuser

---

src/modules/dummypythonqt/main.py

Fix pep8 whining in module dummypythonqt

---

src/modules/removeuser/main.py

Fixed removeuser

---

src/modules/hwclock/main.py

Fixed pep8 whining in module hwclock

---

src/modules/mount/main.py

Fixed pep8 whining in module mount

---

src/modules/luksopenswaphookcfg/main.py

Fixed pep8 whininig in module luksopenswaphookcfg

---

src/modules/initcpiocfg/main.py

Fixed pep8 whining in module initcpiocfg

---

src/modules/initramfs/main.py

Fixed pep8 whining in modulde initramfs

---

src/modules/networkcfg/main.py

Fixed pep8 whining in module networkcfg

---

src/modules/initramfscfg/main.py

Fixed pep8 whining in module initramfscfg

---

src/modules/grubcfg/main.py

Fixed pep8 whining in module grubcfg

---

src/modules/unpackfs/main.py

Fixed pep8 whining in module unpackfs

---

man/calamares.1

Add man page

---

src/modules/services/main.py

Fixed pep8 whining in module services

---

src/modules/displaymanager/main.py

Fixed pep8 whining in module displaymanager

---

src/modules/displaymanager/main.py

- no matter if for example **slick-greeter** is installed as "lightdm-slick-greeter" or whatever, launcher in **/usr/share/xgreeters** will be used. 
tested with **lightdm-deepin-greeter** and **slick-greeter**.
- plus some little simplifications
- added Copyright
https://github.com/calamares/calamares/issues/756

[displaymanager] check for installed lightdm greeter and configure accordingly

---

src/modules/initramfs/main.py

This allows it to create a new initramfs, and replace it.
This will better ensure that calamares generated initramfs is used

Correct update-initramfs command

---

src/modules/finished/finished.conf

- fixes commit 74c19fc02d6f3cdf9693dcc35efc75b837a6e3e9
- fixes #829

finished: fix configuration file syntax

---

src/modules/bootloader/main.py

This pr addresses https://github.com/calamares/calamares/issues/842
Let me know if this is what you had in mind.

Clean up bitness check

---

src/modules/users/UsersViewStep.cpp
src/modules/users/users.conf

Document users.conf 
Also added a warning when we use fallaback groups

Document users.conf

---

src/modules/locale/locale.conf

( this time without touching kofler code .. that doesn't seems to be allowed )

locale.conf: explain what all the settings are about

---

src/modules/netinstall/NetInstallPage.cpp

- change the debug output when the errors occurs so
we have a clue what may go wrong

[netinstall]: some more debug

---

src/modules/partition/gui/CreatePartitionDialog.cpp
src/modules/partition/gui/PartitionPage.cpp

This would allow to use scoped C++11 enum.

[partition] Switch to scoped Device enums.

---

src/modules/netinstall/page_netinst.ui

this file has 1 space char indentation except for these lines

consistent indentation

---

src/modules/hwclock/main.py

[modules]: hwclock fix typo

---

src/modules/openrccfg/main.py
src/modules/openrccfg/module.desc
src/modules/openrccfg/openrccfg.conf

renamed openrccfg and cleaned up, due to a new runitcfg module to have a naming schema.

add openrccfg

---

src/modules/partition/CMakeLists.txt
src/modules/partition/core/DeviceModel.cpp
src/modules/partition/core/DeviceModel.h
src/modules/partition/core/PartitionCoreModule.cpp
src/modules/partition/core/PartitionCoreModule.h
src/modules/partition/core/PartitionInfo.cpp
src/modules/partition/gui/CreateVolumeGroupDialog.cpp
src/modules/partition/gui/CreateVolumeGroupDialog.h
src/modules/partition/gui/ListPhysicalVolumeWidgetItem.cpp
src/modules/partition/gui/ListPhysicalVolumeWidgetItem.h
src/modules/partition/gui/PartitionPage.cpp
src/modules/partition/gui/PartitionPage.h
src/modules/partition/gui/PartitionPage.ui
src/modules/partition/gui/ResizeVolumeGroupDialog.cpp
src/modules/partition/gui/ResizeVolumeGroupDialog.h
src/modules/partition/gui/VolumeGroupBaseDialog.cpp
src/modules/partition/gui/VolumeGroupBaseDialog.h
src/modules/partition/gui/VolumeGroupBaseDialog.ui
src/modules/partition/jobs/CreateVolumeGroupJob.cpp
src/modules/partition/jobs/CreateVolumeGroupJob.h
src/modules/partition/jobs/DeactivateVolumeGroupJob.cpp
src/modules/partition/jobs/DeactivateVolumeGroupJob.h
src/modules/partition/jobs/RemoveVolumeGroupJob.cpp
src/modules/partition/jobs/RemoveVolumeGroupJob.h
src/modules/partition/jobs/ResizeVolumeGroupJob.cpp
src/modules/partition/jobs/ResizeVolumeGroupJob.h

Including LVM Volume Group creation GUI and fixing some problems with revert process when the user got an old VG.
[EDIT] Updating PR to include the remaining parts of LVM VG support.

[partition] Finish LVM Volume Group support

---

src/modules/partition/core/PartitionCoreModule.cpp
src/modules/partition/core/PartitionLayout.cpp

This PR fixes 2 bugs in partition size parsing, both related to the custom partition layout additions.

Fix partition layout sizes parsing

---

src/modules/bootloader/main.py

When choosing `systemd-boot` as the bootloader, numerous problems
occurred:
- the kernel and initrd were not copied to the EFI System Partition,
and therefore could not be reached by the bootloader
- the fallback entry used the default initramfs image instead of the
fallback image
`systemd-boot` provides the `kernel-install` utility, which
automatically copies the kernel + initramfs to the EFI partition, and
creates the corresponding bootloader entry.
Unfortunately, `kernel-install` cannot be used here as the module is not
executed in a chroot. As setting up one only for running a single
command would be overkill, this patch re-creates what `kernel-install`
usually does:
- copy the kernel and initramfs to their own subdirectory at the root of
the EFI partition
- create the corresponding …

[bootloader] Fix systemd-boot installation

---

src/modules/partition/gui/ChoicePage.cpp

When packaging this for Lubuntu I had a lintian warning.

Fix spelling typo

---

settings.conf
src/libcalamares/Settings.cpp
src/libcalamares/Settings.h
src/libcalamaresui/ViewManager.cpp

Implementation of #1122 using the patch by @abucodonosor

Patch to add 'dont-cancel' setting to disable Cancel only during the installation phase

---

src/libcalamaresui/ViewManager.cpp

this addresses feature request #1182
this commit adds a button to the failure MessageBox which posts the install log to termbin.com - this approach has the extra advantage of the back-end (fiche) being freely licensed and easy to self host, if one wants the posts to be private, for example

implement post log to paste server

---

src/modules/fstab/fstab.conf
src/modules/fstab/main.py

This should fix #1198 
The first commit fixes some flake8 errors.
The second commit adds the new configuration option.

Esp mount options

---

src/modules/mount/main.py

When working with a read-only rootfs, we might need to mount a tmpfs (defined as an 'extra mount') where we'll create the mountpoints for other partitions. Unfortunately, the extra mounts are only mounted after each partition has been successfully, which might not be possible in this case.
The `mount` module is therefore modified so that any extra mount gets mounted right after the rootfs.

mount: Make sure extra mounts are mounted right after /

---

src/modules/initcpio/initcpio.conf

```
```
there are more than one now

update doc comment in src/modules/initcpio/initcpio.conf

---

src/modules/displaymanager/main.py

exec changed compared to earlier 5.x

[displaymanager] map plasma 5.17+ desktop environment

---

settings.conf
src/modules/notesqml/CMakeLists.txt
src/modules/notesqml/NotesQmlViewStep.cpp
src/modules/notesqml/NotesQmlViewStep.h
src/modules/notesqml/notesqml.conf
src/modules/notesqml/notesqml.qml
src/modules/notesqml/notesqml.qrc

included in settings.conf, commented out

adding notesqml, copy of dummyqml

---

src/modules/luksbootkeyfile/LuksBootKeyFileJob.cpp

Many thanks in advance for reviewing.

Fix minor typo

---

src/modules/partition/gui/PartitionViewStep.cpp

Many thanks in advance for reviewing.

Fix typo: partitons -> partitions

---

AUTHORS

Perhaps @bill-auger should be considered a reviewer here XD

there's only one bill auger, and we should spell his name right

---

src/libcalamares/locale/Label.cpp
src/libcalamares/locale/Label.h
src/libcalamares/locale/TimeZone.cpp
src/libcalamares/locale/TimeZone.h
src/modules/locale/CMakeLists.txt
src/modules/locale/Config.cpp
src/modules/locale/Config.h
src/modules/localeq/CMakeLists.txt
src/modules/localeq/LocaleQmlViewStep.cpp
src/modules/localeq/LocaleQmlViewStep.h
src/modules/localeq/localeq.conf
src/modules/localeq/localeq.qml

work to make locale view step work with qml. so some models were modified to adjust them and make it usable on qml. also added the conf files to locale to be used later on qwidgets too

Locale module

---

src/modules/welcome/CMakeLists.txt
src/modules/welcome/Config.cpp
src/modules/welcome/Config.h
src/modules/welcomeq/WelcomeQmlViewStep.cpp

updates welcome to work with qml. updated from latest from upstream master

Welcome module

---

src/modules/welcomeq/WelcomeQmlViewStep.cpp
src/modules/welcomeq/welcomeq.qml

welcomeq buttons connecting

---

src/modules/welcomeq/Recommended.qml
src/modules/welcomeq/Requirements.qml
src/modules/welcomeq/about.qml
src/modules/welcomeq/welcomeq.qml
src/modules/welcomeq/welcomeq.qrc

just QML, no real connections yet
hardcoded to not visible
not clear if requirementsModel is available to welcomeq

start of adding requirements to welcomeq

---

src/modules/welcomeq/Recommended.qml
src/modules/welcomeq/Requirements.qml
src/modules/welcomeq/welcomeq.conf
src/modules/welcomeq/welcomeq.qml

clean up obsolete lines in welcomeq.qml
add requirement section from welcome.conf to welcomeq.conf
data shows correctly in Recommended.qml, fails to show any in Requirements.qml if run without admin rights

[welcomeq] connected to RequirementsModel

---

src/modules/partition/core/PartitionActions.cpp

- Unused since commit 0d284759f59a2e1c282f86255d3da8d4542fce9d

[partition] Remove unused locals

---

.gitignore
src/modules/packages/main.py

Add the `tags` file created by vim to `.gitignore`

Gitignore tags
