calamares/calamares

src/modules/partition/gui/CreatePartitionDialog.cpp, src/modules/partition/gui/CreatePartitionDialog.ui, src/modules/partition/gui/EditExistingPartitionDialog.cpp, src/modules/partition/gui/EditExistingPartitionDialog.ui
Remove fixed mountpoint list in the .ui file and create a list of mount points including the customizable efi mount point, when running in an efi capable system.
=> Show efi mountpoint when creating/editing partitions

src/branding/default/branding.desc, src/libcalamaresui/Branding.cpp, src/libcalamaresui/Branding.h, src/modules/greeting/GreetingPage.cpp
URL is a variable set in branding.desc, distros cna link to a Known Issues page
text for the URL is also possible to set in branding, known issues is default
advantage is any text possible as distros see fit
disadvantage, not part of translated strings
if most agree, Known Issues can be set as hard coded text, not in branding.desc
=> add URL option in greeting page

src/modules/grubcfg/main.py
Use 'which' to find plymouth instead of hard coding /usr/bin
Debian ships plymouth in  /bin instead of /usr/bin, so we should use
'which' to figure out if it's installed.
=> Use which to find plymouth instead of hard coding /usr/bin

src/modules/packages/main.py, src/modules/packages/packages.conf
Courtesy of @Inkane. Adds the ability to use pacman -U to install
local packages.
Note: the `local_install` option in the YAML will work for pacman only,
until someone edits `install` to support the rest.
=> Allow local installs with the packages module

src/modules/bootloader/main.py, src/modules/unpackfs/main.py
**'src/modules/bootloader/main.py'**
Contained 'close' functions after 'with'.  'with' will auto-close files so this is not needed.
**'src/modules/unpackfs/main.py'**
'PATH_PROCFS' was being opened, read, closed and then reopened later on without being closed... This resolves that and neatens it up a bit.
=> Small Python IO Cleanup

.editorconfig, HACKING.md
This adds a '.editorconfig' file and a reference to the config within 'HACKING.md'.  [EditorConfig](http://editorconfig.org/) is a simple config file that defines a basic style guide for the project.  The EditorConfig plug-in (that is available for most popular editors) will read the config and automatically adjust its settings to match the style guide.
I figure this is a simple addition to assist future contributers with staying within the 'HACKING' guidelines.
=> EditorConfig

src/modules/webview/CMakeLists.txt, src/modules/webview/WebViewStep.cpp, src/modules/webview/WebViewStep.h, src/modules/webview/module.desc, src/modules/webview/webview.conf
Add a webview module so that calamares can load a webpage.
This is useful when configuring webservices on your device such as
ownCloud.
=> Add a webview module

src/modules/services/main.py, src/modules/services/services.conf
There might be some services that are enabled in live environment but
not useful for the installed environment and needs disabling by default
=> Allow to disable services

src/modules/users/CreateUserJob.cpp, src/modules/users/CreateUserJob.h, src/modules/users/UsersPage.cpp, src/modules/users/UsersPage.h, src/modules/users/UsersViewStep.cpp, src/modules/users/UsersViewStep.h, src/modules/users/users.conf
Fixes CAL-345.
Changing group of home dir to the default "users" group might be a security risk
because every user which belongs to the default "users" group
might be able to access private data on home dirs of other users.
=> CAL-345: don't set default "users" group on home dirs

src/modules/partition/core/PartitionModel.cpp
Tooltip has partition path, file system type, size of partition:
=> Showing a tooltip on hover in Partition Labels

src/modules/umount/README.md, src/modules/umount/main.py, src/modules/umount/umount.conf
instead of having to hope users save an installation log before leaving live mode,
this commit gives distributions the option to have a full calamares -d log available on
the newly installed system
see the readme.md for details
this is fully tested and working properly, using the example launcher script & .desktop line
as noted in the readme
=> Creating the option to copy an install log to target

src/modules/users/UsersPage.h
Input validation for Hostname accept a letter or a digit as the first character to conform to [rfc1123](http://tools.ietf.org/html/rfc1123#page-13 ) . Fixing [CAL-346](https://calamares.io/bugs/browse/CAL-346)
=> Modify Hostname input validation to accept number as first character

src/modules/bootloader/main.py
Read the UEFI bitness exposed to the file system and install the correct
variant of Grub, depending on the UEFI bitness.
=> Enable support for 32bit UEFI systems with Grub

src/modules/partition/gui/PartitionPage.cpp, src/modules/partition/gui/PartitionPage.h
FIX bug: [[CAL-361](https://calamares.io/bugs/browse/CAL-361)]
I take this approach because the bootLoadercomboBox's currentTextChanged signal triggered both when it's users manually selecting or repopulation of the core reset. It makes it hard to differentiate between the two and mark the widget as dirty accordingly, so I only save the index right before the core reset happen and select it back right after the core reset.
=> Disk selections in partitioner are not sticky[CAL-361]

src/modules/packages/main.py
emerge -C means remove package without checking for reverse dependencies. So in order to properly remove calamares and ALL it's reverse dependencies during system installation, one must provide a rather long list in packages module configuration.
faster way to do this is using emerge --depclean -q. It will check for reverse dependencies of packages removed with emerge -C and will clean the system. 
this line was inspired by apt backend, that uses a similar approach
=> improve portage backend, so that properly removes reverse deps, whitout the need of HUGE package list in packages module configuration

src/modules/displaymanager/main.py
displaymanager: write processed DM list to globalstorage so other modules can use it.
Perhaps a detection module would make sense later on, that only writes to globalstorage and collects information, eg DM or init system.
Not sure the required line in module.desc can be used to create depends? Our postcfg module consumes new global storage DM @teo
=> displaymanager: write processed DM list to globalstorage

settings.conf, src/modules/grubcfg/main.py, src/modules/plymouthcfg/main.py, src/modules/plymouthcfg/module.desc, src/modules/plymouthcfg/plymouthcfg.conf
This module is used by **Manjaro Linux** to configure plymouth. It is designed to be used optionally.
* introduces globalstorage variable **hasPlymouth**
* adds new module **plymouthcfg**
=> [plymouthcfg] add module to configure Plymouth

src/modules/users/CreateUserJob.cpp
Pass the full name directly to useradd instead, using the `-c` (comment) parameter, which is "currently used as the field for the user's full name" according to the documentation.
The chfn utility is no longer installed by default on current Fedora releases due to its dependency on libuser. (They split out chfn and chsh from util-linux into an optional subpackage.) It could be added as a dependency of Calamares, but since it is needed inside the chroot, it has to be on the base live image, not the overlay. Thus, to allow testing Calamares with a simple `dnf install calamares` again, the dependency needs to go away. And it is unnecessary anyway.
=> users: Drop dependency on chfn.

src/modules/locale/LocaleConfiguration.cpp, src/modules/locale/LocaleConfiguration.h, src/modules/locale/LocalePage.cpp, src/modules/packages/main.py
This allows for installing locale packages. This can be achieved
by adding a entry of the format packagename-${LOCALE} in the
packages configuration module.
=> Allow passing a LOCALE variable in the package list

src/modules/partition/gui/CreatePartitionDialog.cpp, src/modules/partition/gui/CreatePartitionDialog.h, src/modules/partition/gui/CreatePartitionDialog.ui, src/modules/partition/gui/EditExistingPartitionDialog.cpp, src/modules/partition/gui/EditExistingPartitionDialog.h, src/modules/partition/gui/EditExistingPartitionDialog.ui, src/modules/partition/gui/PartitionPage.cpp, src/modules/partition/gui/PartitionPage.h
When creating/editing a partition, get a list of mountpoints that were already "assigned" to other partitions (minus the current one, if it exists). In case the user tries to assign one of these mountpoints in the dialog, display an italic error message just below the combo box, and disable the Ok button of the dialog.
This fixes https://calamares.io/bugs/projects/CAL/issues/CAL-58
Tested in a Virtualbox with Chakra.
=> Disallow assigning the same mountpoint to two partitions

src/modules/partition/gui/PartitionPage.cpp
Using activated signal may use single or double click depending on environment settings.
At Manjaro we tested with **sudo** only. There it is always double-click also without our patch. However by using **sudo -E** or **pkgexec** with [additional theme patch](https://github.com/manjaro/packages-extra/blob/master/polkit/x11vars.patch) it always resulted in the way how the environment settings were configured for mouse behaviour.
This patch fixes it, to have always double-click for selecting partitions.
=> partition: use always double click to activate a partition tree view item

src/modules/netinstall/README.md, src/modules/packages/test.yaml
The docs do not current reflect the new net-install and packages modules changes well. This updates them to explain the new keys in the configuration files.
=> Updated docs to better explain new features

src/modules/packages/main.py
if the key "install" was used, the install would crash as the backwards compatibility checks were incorrect.
Fixes a typo in the run function so pre- and post-install hooks now work correctly
=> Fixes two bugs in packages module

src/modules/bootloader/main.py
to make it short - it doesn't help much if one tries to find and process any
EFI related things in the live system. The better approach is to search in
the chroot.
=> WIP: fixes #692  bootloader module fails when /EFI/Boot exists

.travis.yml
Reason: pycodestyle is the successor of pep8, same team, same program
different name
https://github.com/PyCQA/pycodestyle
```
/home/travis/build/calamares/calamares/src/modules/bootloader/main.py:113:35: W503 line break before binary operator
/home/travis/build/calamares/calamares/src/modules/bootloader/main.py:114:35: W503 line break before binary operator
/home/travis/build/calamares/calamares/src/modules/bootloader/main.py:115:35: W503 line break before binary operator
/home/travis/build/calamares/calamares/src/modules/bootloader/main.py:117:35: W503 line break before binary operator
/home/travis/build/calamares/calamares/src/modules/bootloader/main.py:318:13: W503 line break before binary operator
```
with the latest pep8 changes it isn't a warning anymore - it's now the preferred …
=> Switch from pep8 to pycodestyle

src/calamares/progresstree/ProgressTreeDelegate.cpp, src/libcalamaresui/Branding.cpp, src/libcalamaresui/Branding.h
This commit adds support for distribution to define `sidebarTextHighlight` to their `branding.desc` file, to control the left panel (sidebar) with highlight behind the current step (`isCurrent`) text label.
And here attaches a screenshot showing what the parameter does.
=> calamares: sidebarTextHighlight for branding

src/modules/fstab/main.py, src/modules/mount/main.py
Only the string "fat32" and "fat16" will be replaced with vfat. If an
case sensitive "Fat32" some problems occure:
- mount: partition cannot be mounted (e.g. a fat32 efi partition)
- fstab: system won't even boot because fstab does not know the type "Fat32"
=> Fix unknown partition-type Fat32 at mount and in fstab

src/modules/partition/gui/CreatePartitionDialog.ui, src/modules/partition/gui/EditExistingPartitionDialog.ui
Makes it easier to know which unit Calamares is using when
resizing a partition. The "Create partition" dialog has
it already.
=> Add "MB" suffix to the "edit partition" size box.

src/modules/users/CreateUserJob.cpp
There is no need to force folks haing a random group
bc that is a Distro think. SDDM/GDM works just fine without
having a group for the user to autologin.
Just setup a group in users.conf .. is why we have a configuration
option for that.
=> CreateUserJob: do not force any autologin group

src/calamares/CalamaresWindow.cpp
the 'productLogo' field in src/branding/default/branding.desc is loaded into the 'Branding::ProductLogo' entity in src/libcalamaresui/Branding.cpp but never actually used anywhere in the program - the image entity 'Branding::ProductIcon' that is currently used for the sidebar is the same one that is used for the much smaller WM/DE icon  - it appears that the original intention was for the sidebar image to use the 'Branding::ProductLogo' entity and that the current  'Branding::ProductIcon' was probably a typo - note that it is rendered inside of a 'logoLabel' inside of a 'logoLayout'
=> use orphaned Branding::ProductLogo as sidebar image

src/modules/finished/FinishedViewStep.cpp
- it doesn't make any sense to have restartNowCommand and fallback
set to the same command.
- also fallback should be something generic every init supports
=> finished: use generic shutdown command

.travis.yml
this will (hopefully) prevent downstreams CI from notifying the upstream IRC channel
NOTE: in order to notify IRC, someone from each fork with access to the travis account will need to declare an environment variable in the travis control panel
for the upstream that would be like:
IRC_NOTIFY_CHANNEL with a value of chat.freenode.net#calamares
unrelated: but i noticed some warnings with the .travis.yml
```
$ travis lint ./.travis.yml
Warnings for ./.travis.yml:
[x] in language section: does not support multiple values, dropping python
[x] specified python, but setting is not relevant for cpp
```
=> use private env var for travis IRC notify channel

src/modules/netinstall/NetInstallPage.cpp
- fixes 1d7ad9e0450d0d069b1496de0c412baab7f7fa96 which sets
both header's labels to 0 so 'Name' was always overridden
by Description and Description never displayed
=> NetInstallPage.cpp: fix displaying for Name and Description

src/modules/welcome/checker/RequirementsChecker.cpp
sending now without fixes for /partition/ ( these after KPMcore things )
and /users/ ( will open an extra PR since the configuration file need some fixes too)
=> RequirementsChecker.cpp: rearrange cDebug() output

src/modules/openrcdmcryptcfg/main.py, src/modules/openrcdmcryptcfg/module.desc, src/modules/openrcdmcryptcfg/openrcdmcryptcfg.conf
Unlike systemd, OpenRC doesn't have a cryptsetup-generator which translates crypttab into native units, so one has to configure /etc/conf.d/dmcrypt in order to auto-unlock LUKS partitions (other than /root and swap which are handled by dracut, initcpio, or whatever initramfs generator) during system boot.
This module will allow to have any number of encrypted partitions on distributions using OpenRC. It will gatter the information needed from **globalstorage** and write it into **/etc/conf.d/dmcrypt**, so when OpenRC fires up dmcrypt service, it will unlock the partitions using the crypto_keyfile.bin .
This is an example of what it will write in /etc/conf.d/dmcrypt :
target=luks-152eced5-3a76-4645-8888-3eaab8193185
source=/dev/disk/by-uuid/152eced5-3a76-4645-8888-3eaab8193185 …
=> new module : openrcdmcryptcfg - auto unlock encrypted partitions with OpenRC

src/modules/partition/jobs/CreatePartitionTableJob.cpp, src/modules/partition/jobs/DeletePartitionJob.cpp, src/modules/partition/jobs/FillGlobalStorageJob.cpp, src/modules/partition/jobs/FormatPartitionJob.cpp
Unlike Calamares job, KPMcore job correctly handles the case when partition is actually LVM logical volume.
=> Convert FormatPartitionJob and CreatePartitionTableJob to KPMcore Operations.

src/modules/unpackfs/main.py
but it does without help
Unhandled exeptions are bad in calamares - and backtraces not exactly user-friendly.
=> [unpackfs] skip error check when rm of tmp folder fails

src/modules/localecfg/main.py
The original code does not distinguish the document comments inside the locale.gen file from the real locale list. The language was then enabled from the header comments of the file instead of the correct value in the list.
The new code verify that the complete locale string is just after the first character of the string, enabling only the correct value of the locale list.
An example:
```
#en_US.UTF-8 UTF-8 --> correct section to enable
```
Related to this request:
https://code.chakralinux.org/tools/calamares-chakra/issues/2
=> Enable the correct language in the locale.gen list

calamares.desktop
Users will never want to install the distribution installer from a
software center like KDE Discover or GNOME Software, so exclude it from
the AppStream metadata collection.
=> Never show Calamares in software centers

src/modules/partition/core/DeviceList.cpp, src/modules/partition/gui/CreatePartitionDialog.cpp
Related to: https://github.com/calamares/calamares/issues/887
=> [partition] Ignoring LVM devices in PartUtils::getDevices to prevent installing bootloader in LVM VG.

src/modules/partition/core/DeviceList.cpp, src/modules/partition/core/PartitionCoreModule.cpp
Fixing bug related to https://github.com/calamares/calamares/pull/945, because only bootloader model should ignore devices that aren't of Disk_Device type in PartitionCoreModule::doInit().
=> [partition] Only bootloader model should ignore devices that are not of Disk_Device type

src/libcalamaresui/modulesystem/ModuleManager.cpp
this patch allows the warning message to display the name of the failing module before throwing just as the preceding "Q_ASSERT( thisModule );" does
=> move thisModule->isLoaded assert to after it's warning message

src/modules/netinstall/netinstall.conf
groupsUrl is optional and should be commented out by default - also this URL is 404 - also only chakra would ever want to ping the chakra server anyways
=> avoid pinging hard-coded server for netinstall.yaml

src/libcalamaresui/modulesystem/PythonQtViewModule.cpp
On pythonQt modules, configuration values aren't python context.
This patch append configuration by PythonQt library on calamares module.
=> Add configuration values into pythonqt modules

src/libcalamaresui/viewpages/PythonQtViewStep.cpp, src/libcalamaresui/viewpages/PythonQtViewStep.h
PythonQt plugins don't have support to Activate and Leave events. This patch adds these events.
=> add support onLeave and onActivate to pythonqt plugins

src/modules/displaymanager/main.py
Closes #1016.
Also note this has been submitted downstream in Ubuntu version 3.2.1-1ubuntu3.
=> Fix default desktop environment variable in displaymanager. 

src/modules/grubcfg/main.py
Hi!
Previously, GRUB tried to decrypt the rootfs disk even if there was an unencrypted /boot partition holding an initramfs.
This is bad because the partition might actually be decrypted with a keyfile or have some other mechanisms involved that require the initramfs to be loaded and cryptsetup itself to unlock the disk.
Therefore, we should only have GRUB involved if the whole disk needs to be decrypted for the system to even start, i.e. if there is no separate /boot partition.
This patch changes grubcfg to check for that partition layout.
Cheers,
Matthias
=> grubcfg: Only try to decrypt disk that /boot is on

src/modules/partition/core/PartitionActions.cpp
having ESP as active flag AND then trying to set ESP means nothing is
set since kpmcore will think ESP is already set (it is listed as active
after all). this ultimately meant that nothing was set since there was
no delta between the requested flags and the already active flags.
=> do not set active flags on the to-be ESP

src/modules/partition/core/PartitionActions.cpp
ESP == boot. at best this is duplicated information, at worst kpmcore may
implode if you try to set a boot flag since that is technically an MBR
type flag and means nothing within the context of GPT where ESP is the flag
to set.
=> do not set boot flag on ESP

src/modules/partition/gui/ChoicePage.cpp, src/modules/partition/gui/ChoicePage.h, src/modules/partition/gui/PartitionPage.cpp, src/modules/partition/gui/PartitionPage.h, src/modules/partition/gui/PartitionViewStep.cpp
The device selected in the choice page (where the user can select "Erase" / "Replace" / ...) is automatically selected by default when switching to the manual partitioning page.
Likewise, any device selection change during manual partitioning will be applied to the choice page in case the user goes back.
Fixes #1043
=> Preserve current device when going to manual partitioning and back

settings.conf, src/libcalamares/Settings.cpp, src/libcalamares/Settings.h, src/libcalamaresui/ViewManager.cpp
In some cases, e.g. when calamares is used as an "initial setup" tool,
we may want the user to go through all the configuration steps in order
to end up with a usable system.
Therefore, disabling the "Cancel" button can be useful in this case.
This commit adds an option to settings.conf which disables this button
when set to "true". If the option is not present in the settings file,
the default behavior ("Cancel" button enabled & visible) is enforced.
=> Add a settings.conf option to disable "Cancel" button

src/modules/rawfs/main.py, src/modules/rawfs/module.desc, src/modules/rawfs/rawfs.conf
In some cases, we might want to copy a filesystem as if we were using a
simple 'dd' command, in order to create an exact copy, down to the block
level.
This can be useful in particular when working with dm-verity for
checking the rootfs integrity: that way, we can make a direct copy of
the rootfs and its verity partition and keep the system usable.
This patch adds a new 'rawfs' module to calamares, making possible to
block-copy a filesystem to a block device.
=> Add a raw filesystem copy module

src/modules/rawfs/main.py
In its current state, the 'rawfs' module requires the source partition 
to be identified either by its mount point or device name, but using a 
symlink to either one (e.g '/dev/disk/by-uuid/...') would fail.
This patch fetches the real path of source partition, allowing the use 
of symlinks.
=> [rawfs] Allow use of symlinks in configuration

src/modules/rawfs/main.py
When using the `rawfs` module for copying data, it may be useful to
save the source device used for later checks or actions. This commit
therefore adds a `source` field to each corresponding partition entry in
global storage, so that this information can be retrieved later during
the installation process.
Another small improvement is that global storage is now modified only
once (it was previously modified as many times as there were entries
processed by the `rawfs` module).
=> [rawfs] Add rawfs source to the `partitions` entry in global storage

src/modules/partition/core/PartUtils.cpp, src/modules/partition/core/PartUtils.h, src/modules/partition/core/PartitionLayout.cpp, src/modules/partition/core/PartitionLayout.h, src/modules/partition/gui/PartitionViewStep.cpp
When using the default partition layout (only a `/` partition), the
filesystem used was ext4, ignoring the `defaultFileSystemType`
configuration option.
This commit fixes this bug, so that any supported filesystem can now be
used for the default partitioning scheme.
Fixes #1093
=> Fix default fs

src/calamares/CalamaresWindow.cpp, src/modules/finished/FinishedPage.cpp, src/modules/finished/FinishedPage.ui, src/modules/finished/FinishedViewStep.cpp, src/modules/plasmalnf/PlasmaLnfPage.cpp, src/modules/summary/SummaryPage.cpp, src/modules/users/UsersPage.cpp, src/modules/users/page_usersetup.ui, src/modules/welcome/checker/GeneralRequirements.cpp
This PR changes the window title in setup mode, and tweaks messages & UI texts for the following modules:
- finished
- users
- plasmalnf
- summary
- welcome
The `tracking` module texts contain the word *installation*, but in a sense that don't seem likely to cause any confusion, it has therefore been left untouched.
Other modules do not contain reference to the installation process or are not likely to be used in setup mode (e.g. the `partition` module).
=> Complete setup mode messages adjustements

src/modules/partition/core/PartitionCoreModule.cpp, src/modules/partition/core/PartitionLayout.cpp, src/modules/partition/core/PartitionLayout.h, src/modules/partition/partition.conf
When using a custom partition layout with partition sizes in %, it can
be useful to set an upper limit to the partition size.
For instance, using a 20% size for the `/` partition will create a 24GB
partition on a 120GB drive, but a 200GB partition on a 1TB drive, which
is not useful, and could be avoided by setting a maximum partition size.
This commit adds the `maxSize` parameter (with a default value of 100%).
=> [partition] Add max size parameter

AUTHORS, src/modules/partition/core/PartitionCoreModule.cpp
To scan LVM devices, it was needed to call LvmDevice::scanDevices from kpmcore before. However, there is a change in this API, as we need to force the scanning of the other types of volume groups before scanning LVM, because it needs to check for PVs in other devices and some clients may call this API without considering these other types of volume groups. This scanning process now is done using VolumeManagerDevice::scanDevices to force the scanning of all the types of volumes groups before LVM.
=> [partition] Fixing LVM scanning according to new kpmcore API

src/libcalamaresui/ExecutionViewStep.cpp
In the sidebar, the "Install" step should be named "Set Up" when in
setup mode, which will be more consistent with the other UI texts,
including button labels.
=> [libcalamaresui] Fix sidebar label for setup mode

src/libcalamares/Job.cpp, src/libcalamares/Job.h, src/libcalamares/JobQueue.cpp
this addresses feature request #1176 
this commit adds a getter method to the Job class,
allowing each sub-class to define a weighted share of
the total 100% progress, and an instance var to the
JobThread class that caches them
the jobPercent as passed into the JobThread::emitProgress()
handler is compared to the defined weight f the current job,
and added to all previous job weights, rather than the current linear
calculation (m_jobIndex / jobPercent)
for any Job sub-class not implementing the getter, the
default value will reproduce the original current behavior as
1/n_jobs
the caveat for the implementer, is that it requires the long
running command to be run in its own thread; so that 'emit
progress' can be pumped in fine grained intervals - and of
course there needs to be some way to …
=> implement definable job weights

src/libcalamares/PythonHelper.cpp, src/libcalamares/partition/PartitionSize.cpp, src/libcalamares/utils/NamedSuffix.h, src/libcalamares/utils/Variant.cpp, src/libcalamares/utils/Variant.h, src/libcalamares/utils/Yaml.cpp, src/modules/welcome/checker/GeneralRequirements.cpp
For the `partition` module, we might need to parse extremely large numbers (such as a multi-GiB sizes expressed in bytes), resulting in an overflow for 32-bit integers.
In order to solve this, this patch modifies `CalamaresUtils::getInteger()` in order to return a `qint64`.
=> Prevent integer overflow when parsing configuration

src/modules/unpackfs/main.py
In some (rare) cases, `num_files_total_local` might not be declared when reporting progress. This patch initializes this variable in order to prevent any python error in this case.
=> Fix error in unpackfs

src/libcalamares/partition/PartitionSize.cpp, src/libcalamares/partition/PartitionSize.h, src/libcalamares/utils/Units.h
In order to improve compatibility with third-party software, we could use a way to define partition sizes in 'base 10' multiples, namely kilo-, mega- & giga- (only 'base 2' multiples kibi-, mibi- & gibi- are supported for now).
Additionally, this PR modifies the `bytesToSectors()` function, so that partitions get aligned on sector boundaries, not necessarily on 1MiB blocks.
=> Add 'base 10' partition size multiples

src/modules/locale/LocaleViewStep.cpp, src/modules/locale/locale.conf, src/modules/welcome/welcome.conf
mainly to clarify that geoip requests can originate from two different modules for those who wish to disable it
=> cross-reference/clarify geoip documentation

src/modules/welcome/WelcomePage.cpp
this is a patch i am carrying - the hard-coded index is problematic if any custom elements are added to the page - for instance, i added a banner image above the welcome message - i could append that patch too if others want it - the banner image element is added only if it is defined in the branding config
=> eliminate magic number in src/modules/welcome/WelcomePage.cpp

src/branding/default/lang/calamares-default_ar.ts, src/branding/default/lang/calamares-default_en.ts, src/branding/default/lang/calamares-default_eo.ts, src/branding/default/lang/calamares-default_fr.ts
all of these translations other than english were declared as 'nl'
=> add esperanto branding translations, fix mis-configured ones

src/modules/unpackfs/main.py
If we don't have/need an image for the rootfs, we might want to
configure the `/` directory as a source for unpackfs. Unfortunately,
this raises an error:
- unpackfs first creates a temporary directory
- it then creates a subdirectory for each source, using the source
path's basename
- when the source is `/`, the basename is an empty string, therefore
the module tries to create an already existing directory
In order to prevent this error, we use the `os.makedirs` function with
parameter `exist_ok=True` instead of `os.mkdir`.
=> [unpackfs] Enable to use "/" as a source

src/modules/users/UsersPage.cpp, src/modules/users/UsersPage.h, src/modules/users/UsersViewStep.cpp, src/modules/users/page_usersetup.ui, src/modules/users/users.conf
this is useful for grown-up users (and devs) to be able to use weak passwords if they so choose, while keeping the constraints enabled by default - it currently only guards the libpwquality checks; and is hidden when libpwquality is not linked in
=> add checkbox to disable password validations

src/modules/packagechooser/packagechooser.conf
the second commit only changes white-space for readability
=> fix typos in src/modules/packagechooser/packagechooser.conf

src/modules/welcome/checker/ResultsListWidget.cpp
with dark themes, the failed requirement notice and pop-out message-box have un-readable white-on-white text - this is due to the hard-coded text color Qt::white
this MR applies a red-ish tint to whatever is the current background color beneath the warning text for failed mandatory checks, and a yellow-ish tint for failed optional checks - i made the change from 'QPalette::Background' to 'QPalette::Window' due to the deprecation notice on the QT docs website
this code could use to be dried out - i have more commits which do that if you want to see them - in fact, this ResultsListWidget is the only client of ResultWidget; so all of the configuration which is duplicated for both instances, could be moved into the ResultWidget constructor
=> replace hard-coded bg color of requirements failure notice with relative tint

src/modules/initcpiocfg/main.py
The hook **usr** adds support for `/usr `on a separate partition when using **mkinicpio**. See [#/usr as a separate partition](https://wiki.archlinux.org/index.php/Mkinitcpio#/usr_as_a_separate_partition) for details. Function: Mounts the `/usr `partition after the real root has been mounted.
=> [initcpiocfg] add usr hook if partition is separate

src/modules/packagechooser/PackageChooserPage.cpp, src/modules/packagechooser/PackageChooserPage.h, src/modules/packagechooser/PackageChooserViewStep.cpp, src/modules/packagechooser/PackageChooserViewStep.h, src/modules/packagechooser/packagechooser.conf
while evaluating the 'packagechooser' module, i noted some things that i did not like - one of them being that there was no way to have a static description/explanation of the module - the other more importanlty thing was that there is no way to pre-select a default list item - that would be quite useful, especially in "required" modes -
this MR accomplishes both of those features, while retaining the original behavior, if desired; by adding two new config keys to over-ride the existing null item method, if desired
the documentation for the 'item['id]' indicates that it is not intended to be used in 'required' modes
> Only include this if the mode allows selecting none.
for that reason, this MR also removes the null item if present and in one of the 'required' modes, regardless of the new …
=> pre-select default item in packagechooser

src/modules/packages/main.py, src/modules/packages/packages.conf
Yay for easy Python scripting!
Since we're looking into using Calamares as on-device installer for postmarketOS, let's add support for the Alpine Linux (which postmarketOS is based on) package manager.
Is this the only required bit as far as packages go, or is there some other things that need specific Alpine Linux support to work?
=> [packages] Add apk (Alpine Linux package manager) support

src/libcalamares/CMakeLists.txt, src/modules/fsresizer/CMakeLists.txt, src/modules/partition/CMakeLists.txt, src/modules/partition/core/PartitionCoreModule.cpp, src/modules/partition/core/PartitionLayout.cpp, src/modules/partition/core/PartitionLayout.h, src/modules/partition/partition.conf
_KPMcore_ is now supporting for filesystem-specific features since the version _4.1.0_.
The file-system __features__ can be set using the module partition by specifying the dictionary `features` for any partition in `partitionLayout`. The feature is specific to the filesystem; the feature as a name and a value that can be either a boolean flag or an integer value or a string.
The example below tests the boolean and integer values feature. It:
- sets the both _FAT32_ features `sector-size` and `sectors-per-cluster` that take an integer value to the partition _efi_, and
- sets the _ext4_ feature `casefold` and resets the _ext4_ feature `64bit` that are two boolean flags to the partition _rootfs_. 
``` yaml
$ cat partition.conf
(...)
partitionLayout:
- name: "efi"
filesystem: "fat32" …
```
=> [partition] Add support for filesystem-specific features

src/modules/partition/core/PartitionLayout.cpp, src/modules/partition/partition.conf
Hello,
This PR reuses the attribute `name` to name the GTP partition; the `name` is used already to set the filesystem label.
``` yaml
partitionLayout:
- name: "efi" # set the filesystem label to "efi" AND the gpt partition name to "efi" as well
filesystem: "fat32"
- name: "rootfs" # ditto with "rootfs"
filesystem: "ext4"
```
The example above creates the following GPT disk:
```
label: gpt
label-id: X
device: /dev/sda
unit: sectors
first-lba: X
last-lba: X
sector-size: 512
/dev/sda1 : start=X, size=X, type=X, uuid=X, name="efi"
/dev/sda2 : start=X, size=X, type=X, uuid=X, name="rootfs"
```
This MR needs the [MR](https://invent.kde.org/kde/kpmcore/-/merge_requests/4) to be merged in KPMCore to be functional, but it does not require it to compile.
Regards,
Gaël
=> [partition] Name partition using filesystem label

src/modules/localeq/localeq.qml
probably due to dynamically loading items
regionModel now lists, zonesModel only lists one delegate, but
working on QML modules can now continue without crashing cala
=> [localeq] Repeater with zonesModel crashes cala

src/modules/partition/jobs/FillGlobalStorageJob.cpp
The mount-point is known as mountPoint in the global storage.
This commit updates the trace to reflect its real name.
=> [partition] Update debug output

src/modules/bootloader/main.py
- This forces the EFI firmware to boot the loader that was just
created, whatever the boot order set in the firmware setup (USB,
CD/DVD, HD...).
- It is safe to use the first Boot Entry listed in BootOrder as the
previous command creates the new entry and adds it to the first place
of the BootOrder.
=> [bootloader] Set the EFI Boot Next

src/modules/bootloader/main.py
- root_mount_point was used initially for logging c1a139995 (adding new
bootloader job options are to use grub for BIOS, gummiboot for efi set
extra mountpoint when efi is found)
- the trace was removed since 533031b3c ([bootloader] print() does not
log)
=> [bootloader] Remove unused variable root_mount_point

src/modules/rawfs/main.py
Hello,
I found a crash with the module `rawfs`.
This happens since 74fb88f9ac674ccbe2aacf2e6a9e1298b692c50c if the new property `bogus` is unset, that is the case with the files `rawfs.conf` written before calamares version 3.2.24.
This fixes
```
12:44:25 [6]: Python Error:
<class 'TypeError'>
'builtin_function_or_method' object is not subscriptable
File "/usr/lib/calamares/modules/rawfs/main.py", line 188, in run
item.copy(filesystems.index(item), len(filesystems))
File "/usr/lib/calamares/modules/rawfs/main.py", line 99, in copy
if libcalamares.job.configuration["bogus"]:
```
Best Regards,
Gaël
=> [rawfs] Fix crash if bogus is unset

src/modules/partition/core/PartitionCoreModule.cpp, src/modules/partition/core/PartitionLayout.cpp, src/modules/partition/core/PartitionLayout.h, src/modules/partition/jobs/FillGlobalStorageJob.cpp, src/modules/partition/partition.conf
Hello,
This PR adds the attribute `uuid` that sets the `PARTUUID` to the GPT partition (
b3400b7) and adds the GPT `partlabel` and `partuuid` to the global storage (5cb0024).
This PR requires the [MR](https://invent.kde.org/kde/kpmcore/-/merge_requests/8) to be merged in KPMCore. Merged.
Regards,
Gaël
=> Partition UUID

src/libcalamares/utils/Variant.cpp, src/libcalamares/utils/Variant.h, src/modules/partition/core/PartitionCoreModule.cpp, src/modules/partition/core/PartitionLayout.cpp, src/modules/partition/core/PartitionLayout.h, src/modules/partition/partition.conf
Hello,
This PR adds the attribute `attributes` that sets the GPT attributes to the GPT partition.
This PR requires the [MR](https://invent.kde.org/system/kpmcore/-/merge_requests/9) to be merged in KPMCore. Merged.
This PR is similar to #1409 for GPT partition UUID (`PARTUUID`).
Regards,
Gaël
=> Partition Attributes

src/modules/partition/core/Config.cpp, src/modules/partition/core/Config.h, src/modules/partition/core/PartitionActions.cpp, src/modules/partition/core/PartitionActions.h, src/modules/partition/gui/ChoicePage.cpp, src/modules/partition/gui/ChoicePage.h, src/modules/partition/gui/PartitionViewStep.cpp, src/modules/partition/gui/ReplaceWidget.cpp, src/modules/partition/partition.conf
Hello,
This PR ~~is an _RFC_ to~~ restricts the installation on disks that use a specified partition table.
For example, since the `systemd` 211and the service [systemd-gpt-auto-generator](https://www.freedesktop.org/software/systemd/man/systemd-gpt-auto-generator.html), it is possible to discover and mount various partitions based on the _GPT_ [type](https://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec/).
Therefore, we want to make sure the operating system is installed on a _GPT_ disk.
For now, the option **Erase disk** creates a new _GPT_ partition table if the booted system is _EFI_; otherwise, it creates an _MBR/MSDOS_ partition table (legacy _BIOS_).
The options **Replace a partition** and **Install alongside** left untouched the partition table type that …
=> [partition] Partition table type settings
